### PR TITLE
Init lite client connection from config file

### PR DESCRIPTION
**Pull request by zloylos**

### CODE REVIEW

**Comment by xssnick** [comment]
Thank you, I will merge it in next release.

**Comment by denis-hananein** [comment]
@xssnick ping

**Comment by xssnick** [comment]
I remember :) 

Wanted to merge it with next major (1.8) release, but if it is urgent, I can merge to dev branch and you could import from it

**Comment by denis-hananein** [comment]
It's ok, just wanted to know that you didn't forget :)

**Pull request merged**
