### PR TITLE
Added optional signer for wallet

### PR DESCRIPTION
**Pull request by nayutalienx**
Hello, the task was to teach the library to sign transactions using an external provider, since the keys are not always in the open. This code was tested on regular TON transfers and transfers in jettons.

### CODE REVIEW

**Comment by xssnick** [comment]
Hi, thank you for PR, feature looks useful!

But lets pass cell to signer instead of hash, so it can know what it is signing and can use cell.Sign method

**Comment by nayutalienx** [comment]
Thanks for the feedback! I've updated the PR. Let me know if there's anything else you'd like me to adjust.

**Comment by xssnick** [comment]
Thank you, also I think it would be useful to pass context to signer, since it can be remote

**Comment by nayutalienx** [comment]
Done.

**Comment by nayutalienx** [comment]
> @nayutalienx Hi! How did u manage with lib's internal private time.Now call for TTL? Its must to use the same values were during signature time to match signature

Hi, I don't quite understand what problem you're talking about. The input data for signing a transaction is a hash in the form of a byte array. This hash is provided by cell. The signing algorithm is in the standard library ed25519. What ttl has to do with it is not entirely clear.

**Pull request merged**
